<a href="https://colab.research.google.com/github/piyush2007ramteke/IAIML/blob/main/practicel3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# -------------------------------
# Part 1: Student Marks Analysis
# -------------------------------

marks = np.array([int(input(f"Enter marks of student {i+1}: ")) for i in range(5)])

print("\nStudent Marks:", marks)
print("Average Marks:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks :", np.min(marks))

# -------------------------------
# Part 2: Matrix Operations
# -------------------------------

print("\nEnter elements for Matrix A (2x2):")
A = np.array([[int(input(f"  A[{i}][{j}]: ")) for j in range(2)] for i in range(2)])

print("\nEnter elements for Matrix B (2x2):")
B = np.array([[int(input(f"  B[{i}][{j}]: ")) for j in range(2)] for i in range(2)])

print("\nMatrix A:\n", A)
print("Matrix B:\n", B)

print("\nMatrix Addition:\n",       A + B)
print("\nMatrix Subtraction:\n",    A - B)
print("\nMatrix Multiplication:\n", np.dot(A, B))

Enter marks of student 1: 50
Enter marks of student 2: 78
Enter marks of student 3: 90
Enter marks of student 4: 89
Enter marks of student 5: 45

Student Marks: [50 78 90 89 45]
Average Marks: 70.4
Highest Marks: 90
Lowest Marks : 45

Enter elements for Matrix A (2x2):
  A[0][0]: 2
  A[0][1]: 3
  A[1][0]: 4
  A[1][1]: 5

Enter elements for Matrix B (2x2):
  B[0][0]: 1
  B[0][1]: 2
  B[1][0]: 3
  B[1][1]: 6

Matrix A:
 [[2 3]
 [4 5]]
Matrix B:
 [[1 2]
 [3 6]]

Matrix Addition:
 [[ 3  5]
 [ 7 11]]

Matrix Subtraction:
 [[ 1  1]
 [ 1 -1]]

Matrix Multiplication:
 [[11 22]
 [19 38]]
